---
openapi_doc_conf:
  paths: >
    /api/udpp/v1/**,
    /api/udppparameters/v1/**
  apigroup: api-v1

openapi_doc:
  title: The Unified Development Power Platform Application
  description: This API service represents the evolution of an older project that generated classes developed in
    Object Pascal using Delphi XE10. The architecture pattern employed in this project is the hexagonal
    architecture.
  version: 1.0
  terms_of_serviceUrl: '-'
  produces: application/json
  license_url: https://www.linkedin.com/in/claudiomildoventura/

openapi_doc_personal_information:
  name: Claudiomildo Ventura
  email: claudiomildo@hotmail.com
  linkedin: https://www.linkedin.com/in/claudiomildoventura/